name1 = input('请输入第一个人的姓名：')
height1 = float(input('请输入第一个人的身高(米)：'))
weight1 = float(input('请输入第一个人的体重(kg)：'))
waistline1 = int(input('请输入第一个人的腰围：'))
name2 = input('请输入第二个人的姓名：')
height2 = float(input('请输入第二个人的身高(米)：'))
weight2 = float(input('请输入第二个人的体重(kg)：'))
waistline2 = int(input('请输入第二个人的腰围：'))
name3 = input('请输入第三个人的姓名：')
height3 = float(input('请输入第三个人的身高(米)：'))
weight3 = float(input('请输入第三个人的体重(kg)：'))
waistline3 = int(input('请输入第三个人的腰围：'))
print('{:10s}{:10s}{:10s}{:10s}'.format('姓名','身高','体重','腰围'))
print('{}{:12.2f}{:12.1f}{:10d}'.format(name1,height1,weight1,waistline1))
print('{}{:12.2f}{:12.1f}{:10d}'.format(name2,height2,weight2,waistline2))
print('{}{:12.2f}{:12.1f}{:10d}'.format(name3,height3,weight3,waistline3))